"
   Licensed under the Squeak License (the ''License''); you may not use this file except in compliance with the License.  You may obtain a copy of the License at  http://www.squeak.org/SqueakLicense/
"!
'From test of 18 May 2008 [latest update: #0] on 18 May 2008 at 3:57:45 pm'!!UndefinedObject methodsFor: '*NsSystem' stamp: 'Ahe 5/18/2008 15:57'!displayProgressAt: ignored1 from: ignored2 to: ignored3 during: workBlock	^workBlock value: [:ignored|]! !