"
   Licensed under the Squeak License (the ''License''); you may not use this file except in compliance with the License.  You may obtain a copy of the License at  http://www.squeak.org/SqueakLicense/
"!
'From nsboot-2008-04-30.00 of 30 April 2008 [latest update: #0] on 1 May 2008 at 12:44:56 pm'!Preferences	addBooleanPreference: #inPackagedImage	category: #NsSystem	default: false balloonHelp: 'Turn on packaging for application delivery'!